Repository DoDreamTeam/Backend, pull requests merged in 2024-11, with the labels that each got.

#124 [기능 수정 - 문제집/댓글] 문제집/댓글 조회 시 북마크 여부 추가
  src/main/java/com/dodream/book/controller/BookCommentController.java
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/domain/BookCommentResponse.java
  src/main/java/com/dodream/book/domain/BookResponse.java
  src/main/java/com/dodream/book/repository/BookCommentLikeRepository.java
  src/main/java/com/dodream/book/repository/BookmarkRepository.java
  src/main/java/com/dodream/book/service/BookCommentService.java
  src/main/java/com/dodream/book/service/BookCommentServiceImpl.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/test/java/com/dodream/book/service/BookCommentServiceTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: 🐞 Bugfix

#126 [버그 수정 - 스터디] 프로필 이미지 이슈 + 좋아요 이슈
  src/main/java/com/dodream/book/repository/UserAnswerRepository.java
  src/main/java/com/dodream/study/controller/NoticeCommentController.java
  src/main/java/com/dodream/study/controller/QueCommentController.java
  src/main/java/com/dodream/study/controller/StudyUserQueAnswerController.java
  src/main/java/com/dodream/study/domain/NoticeCommentResponse.java
  src/main/java/com/dodream/study/domain/QueCommentResponse.java
  src/main/java/com/dodream/study/domain/StudyMemberResponse.java
  src/main/java/com/dodream/study/domain/StudyResponse.java
  src/main/java/com/dodream/study/domain/StudyUserAnswerResponse.java
  src/main/java/com/dodream/study/domain/StudyUserQueAnswerResponse.java
  src/main/java/com/dodream/study/repository/NoticeCommentLikeRepository.java
  src/main/java/com/dodream/study/repository/QueCommentLikeRepository.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/repository/StudyRepository.java
  src/main/java/com/dodream/study/service/NoticeCommentService.java
  src/main/java/com/dodream/study/service/NoticeCommentServiceImpl.java
  src/main/java/com/dodream/study/service/QueCommentService.java
  src/main/java/com/dodream/study/service/QueCommentServiceImpl.java
  src/main/java/com/dodream/study/service/StudyMemberServiceImpl.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/main/java/com/dodream/study/service/StudyUserAnswerServiceImpl.java
  src/main/java/com/dodream/study/service/StudyUserQueAnswerService.java
  src/main/java/com/dodream/study/service/StudyUserQueAnswerServiceImpl.java
  src/test/java/com/dodream/study/service/NoticeCommentServiceTest.java
  src/test/java/com/dodream/study/service/StudyServiceImplTest.java
Labels: 🐞 Bugfix

#129 [기능 개발 - 알림] 알림 기능 개발 + 사용자 알림 CRUD 구현
  src/main/java/com/dodream/book/service/BookCommentServiceImpl.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/notifications/controller/NotificationController.java
  src/main/java/com/dodream/notifications/domain/NotificationResponse.java
  src/main/java/com/dodream/notifications/domain/UpdateNotificationRequest.java
  src/main/java/com/dodream/notifications/domain/UpdateNotificationResponse.java
  src/main/java/com/dodream/notifications/entity/Notifications.java
  src/main/java/com/dodream/notifications/enumtype/NotifyType.java
  src/main/java/com/dodream/notifications/repository/EmitterRepository.java
  src/main/java/com/dodream/notifications/repository/NotificationRepository.java
  src/main/java/com/dodream/notifications/service/NotificationService.java
  src/main/java/com/dodream/study/repository/QueCommentLikeRepository.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/service/QueCommentServiceImpl.java
  src/main/java/com/dodream/study/service/StudyMemberServiceImpl.java
Labels: ✨ Feature

#131 [버그 수정 - 스터디] 공지사항 api 명칭 변경
  src/main/java/com/dodream/study/controller/NoticeController.java
  src/main/java/com/dodream/study/service/NoticeService.java
  src/main/java/com/dodream/study/service/NoticeServiceImpl.java
  src/test/java/com/dodream/study/service/NoticeServiceTest.java
Labels: 🐞 Bugfix

#133 [성능 개선 - 레디스 캐싱] 레디스 캐싱 적용
  src/main/java/com/dodream/study/domain/StudyUserQueAnswerResponse.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/main/java/com/dodream/study/service/StudyUserQueAnswerServiceImpl.java
  src/main/java/com/dodream/util/CustomPageImpl.java
Labels: 🎤 Perform

#135 [버그 수정 - 문제집] 특정 문제집 내가 푼 문제 제외 조회 수정
  src/main/java/com/dodream/book/controller/QuestionController.java
  src/main/java/com/dodream/book/repository/QuestionRepository.java
  src/main/java/com/dodream/book/service/QuestionService.java
  src/main/java/com/dodream/book/service/QuestionServiceImpl.java
Labels: 🐞 Bugfix

#137 [CI/CD] 백엔드 프로젝트 배포
  Dockerfile
  docker-compose.yml
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/main/java/com/dodream/study/service/StudyUserQueAnswerServiceImpl.java
Labels: 🤖 CI/CD

#139 [테스트 코드] 마이페이지 테스트 코드 작성
  src/test/java/com/dodream/mypage/service/MyPageMeServiceImplTest.java
  src/test/java/com/dodream/mypage/service/MyPageServiceImplTest.java
Labels: ✅ Test

#141 [테스트] 문제집 관련 테스트 코드 수정
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookmarkRepositoryTest.java
  src/test/java/com/dodream/book/service/BookCommentServiceTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
  src/test/java/com/dodream/book/service/QuestionServiceTest.java
Labels: ✅ Test

#143 [마이페이지] 레디스 캐싱 + 정적 메소드 생성 #142
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
  src/main/java/com/dodream/util/AwsS3Info.java
Labels: ✨ Feature
