Repository DoDreamTeam/Backend, pull requests merged in 2024-10, with the labels that each got.

#19 [기능 개발-문제집] 문제집 도메인 설계
  src/main/java/com/dodream/book/entity/Book.java
  src/main/java/com/dodream/bookcomment/entity/BookComment.java
  src/main/java/com/dodream/bookcommentlike/entity/BookCommentLike.java
  src/main/java/com/dodream/bookmark/entity/Bookmark.java
  src/main/java/com/dodream/common/enumtype/Category.java
  src/main/java/com/dodream/question/entity/Question.java
  src/main/java/com/dodream/studyanswer/entity/StudyAnswer.java
  src/main/java/com/dodream/user/entity/User.java
  src/main/java/com/dodream/useranswer/entity/UserAnswer.java
  src/main/java/com/dodream/useranswer/enumtype/Evaluation.java
  src/main/java/com/dodream/userbook/entity/UserBook.java
Labels: ✨ Feature

#20 [기능 개발-알림] 알림 도메인 설계
  src/main/java/com/dodream/notifucations/entity/Notifications.java
Labels: ✨ Feature

#27 [테스트 - 스터디] StudyRepository 테스트 코드 작성
  src/main/java/com/dodream/study/repository/StudyRepository.java
  src/main/java/com/dodream/user/entity/User.java
  src/test/java/com/dodream/study/repository/StudyRepositoryTest.java
  src/test/java/resources/resources/application-local.yml
  src/test/java/resources/resources/application-test.yml
  src/test/java/resources/resources/application.yml
Labels: ✅ Test

#29 [기능 개발 - 문제집] 문제집 전체 조회
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/domain/BookResponse.java
  src/main/java/com/dodream/book/repository/BookRepository.java
  src/main/java/com/dodream/book/repository/BookmarkRepository.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
Labels: ✨ Feature

#31 [Test] 문제집 전체조회 테스트 코드 작성
  src/main/java/com/dodream/book/entity/Book.java
  src/main/java/com/dodream/book/entity/BookComment.java
  src/main/java/com/dodream/book/entity/BookCommentLike.java
  src/main/java/com/dodream/book/entity/Bookmark.java
  src/main/java/com/dodream/book/entity/Question.java
  src/main/java/com/dodream/book/entity/UserAnswer.java
  src/main/java/com/dodream/book/entity/UserBook.java
  src/main/java/com/dodream/user/repository/UserRepository.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
Labels: ✅ Test

#33 [기능 개발-마이페이지] 상세 정보 조회
  src/main/java/com/dodream/book/repository/UserBookRepository.java
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/domain/UserInfoResponse.java
  src/main/java/com/dodream/mypage/service/MyPageService.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ✨ Feature

#37 [기능 개발- 문제집 메인 페이지] 카테고리별 문제집 조회
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/repository/BookRepository.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#38 [기능 개발-스터디 전체 조회] 인원수 조회 기능
  src/main/java/com/dodream/study/domain/StudyResponse.java
  src/main/java/com/dodream/study/enumtype/ApplyStatus.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
Labels: ✨ Feature

#39 [기능 개발-비회원 메인 페이지] 소셜 로그인 (Kakao, Naver, Google) + Jwt
  build.gradle
  src/main/java/com/dodream/DodreamSampleApplication.java
  src/main/java/com/dodream/common/config/RedisConfig.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/security/JwtAuthenticationFilter.java
  src/main/java/com/dodream/security/JwtProperties.java
  src/main/java/com/dodream/security/JwtProvider.java
  src/main/java/com/dodream/user/controller/UserController.java
  src/main/java/com/dodream/user/domain/AuthEnum.java
  src/main/java/com/dodream/user/domain/LoginResponse.java
  src/main/java/com/dodream/user/domain/OAuthUser.java
  src/main/java/com/dodream/user/entity/User.java
  src/main/java/com/dodream/user/repository/UserRepository.java
  src/main/java/com/dodream/user/service/UserService.java
  src/main/java/com/dodream/user/service/UserServiceImpl.java
  src/main/java/com/dodream/util/OAuth2Properties.java
  src/main/java/com/dodream/util/TokenUtils.java
  src/main/resources/application-local.yml
Labels: ⚙️ Setting, ✨ Feature

#41 [기능 개발-마이페이지] 프로필 수정
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/domain/UserInfoResponse.java
  src/main/java/com/dodream/mypage/domain/UserUpdateRequest.java
  src/main/java/com/dodream/mypage/service/MyPageService.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ✨ Feature

#43 [테스트-JWT 토큰 생성] JWT 토큰 테스트
  build.gradle
  src/test/java/com/dodream/security/JwtFactory.java
  src/test/java/com/dodream/security/JwtProviderTest.java
Labels: ⚙️ Setting, ✅ Test

#47 [기능 개발 - 문제집 검색 기능, 예외 처리]
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/repository/BookRepository.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/common/exception/ErrorController.java
  src/main/java/com/dodream/common/response/ErrorResponse.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#53 [소셜 로그인-버그 수정] 소셜 로그인 후 사용자 정보가 업데이트 되지 않는 문제
  src/main/java/com/dodream/user/controller/UserController.java
  src/main/java/com/dodream/user/entity/User.java
  src/main/java/com/dodream/user/repository/UserRepository.java
  src/main/java/com/dodream/user/service/UserServiceImpl.java
Labels: 🐞 Bugfix

#54 [기능개발-마이페이지 문제집] 문제집 수정
  src/main/java/com/dodream/book/entity/Book.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/domain/BookUpdateRequest.java
  src/main/java/com/dodream/mypage/domain/BookUpdateResponse.java
  src/main/java/com/dodream/mypage/domain/UserInfoResponse.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor, 💠 Styles

#56 [기능 개발] 문제집 생성
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/domain/BookRequest.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: ✨ Feature, ✅ Test

#58 [기능수정 - 문제집] 최신순으로 정렬
  src/main/java/com/dodream/book/repository/BookRepository.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: 🐞 Bugfix

#59 [기능개발-마이페이지 문제집] 나의 문제집 삭제
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/domain/BookUpdateRequest.java
  src/main/java/com/dodream/mypage/domain/BookUpdateResponse.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ✨ Feature

#60 [기능개발-마이페이지 문제집] 나의 문제집 공개/비공개 설정
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/domain/BookUpdateResponse.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
Labels: ✨ Feature

#66 [버그 수정] 프로필 수정 이후 Jwt 토큰 에러 발생
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/security/JwtProvider.java
  src/test/java/com/dodream/security/JwtProviderTest.java
Labels: 🐞 Bugfix

#67 [리팩토링] 문제집 관련 중복되는 기능
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/domain/BookUpdateRequest.java
  src/main/java/com/dodream/book/domain/BookUpdateResponse.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: 🔧 Refactor

#68 [기능 개발 - 문제집] 문제집 북마크 생성 , 해제
  src/main/java/com/dodream/book/controller/BookmarkController.java
  src/main/java/com/dodream/book/domain/BookmarkResponse.java
  src/main/java/com/dodream/book/repository/BookmarkRepository.java
  src/main/java/com/dodream/book/service/BookmarkService.java
  src/main/java/com/dodream/book/service/BookmarkServiceImpl.java
  src/test/java/com/dodream/book/repository/BookmarkRepositoryTest.java
  src/test/java/com/dodream/book/service/BookmarkServiceTest.java
Labels: ✨ Feature, ✅ Test

#69 [기능개발-마이페이지 문제집] 나의 북마크 문제집목록 추가 , 예외처리 수정
  src/main/java/com/dodream/book/repository/BookmarkRepository.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/domain/UserInfoResponse.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
  src/main/java/com/dodream/mypage/service/MyPageService.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor, 💠 Styles

#72 [기능 개발 - 스터디] 스터디 서비스 개발
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/StudyController.java
  src/main/java/com/dodream/study/domain/StudyRequest.java
  src/main/java/com/dodream/study/domain/StudyResponse.java
  src/main/java/com/dodream/study/domain/StudyUpdateRequest.java
  src/main/java/com/dodream/study/domain/StudyUpdateResponse.java
  src/main/java/com/dodream/study/entity/Study.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/repository/StudyRepository.java
  src/main/java/com/dodream/study/service/StudyService.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
Labels: ✨ Feature, 🎤 Perform

#75 [기능개발-마이페이지 문제집] 나의 문제집 댓글 , 좋아요 조회
  src/main/java/com/dodream/book/repository/BookCommentLikeRepository.java
  src/main/java/com/dodream/book/repository/BookCommentRepository.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/domain/BookCommentLikeResponse.java
  src/main/java/com/dodream/mypage/domain/BookCommentResponse.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
Labels: ✨ Feature

#78 [기능 개발 - 스터디] 내가 참여한 스터디 조회 구현
  src/main/java/com/dodream/study/controller/StudyController.java
  src/main/java/com/dodream/study/domain/StudyRequest.java
  src/main/java/com/dodream/study/domain/StudyResponse.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/service/StudyService.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/test/java/com/dodream/study/service/StudyServiceImplTest.java
Labels: ✨ Feature, ✅ Test

#79 [기능 개발 - 문제집] 문제집 댓글 CRUD
  src/main/java/com/dodream/book/controller/BookCommentController.java
  src/main/java/com/dodream/book/domain/BookCommentRequest.java
  src/main/java/com/dodream/book/domain/BookCommentResponse.java
  src/main/java/com/dodream/book/domain/BookCommentUpdateRequest.java
  src/main/java/com/dodream/book/domain/BookCommentUpdateResponse.java
  src/main/java/com/dodream/book/entity/BookComment.java
  src/main/java/com/dodream/book/repository/BookCommentLikeRepository.java
  src/main/java/com/dodream/book/repository/BookCommentRepository.java
  src/main/java/com/dodream/book/service/BookCommentService.java
  src/main/java/com/dodream/book/service/BookCommentServiceImpl.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/test/java/com/dodream/book/repository/BookCommentRepositoryTest.java
  src/test/java/com/dodream/book/service/BookCommentServiceTest.java
Labels: ✨ Feature, ✅ Test

#81 [기능 개발-문제집 메인 페이지] 최신순, 북마크 많은순 조회
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/controller/BookmarkController.java
  src/main/java/com/dodream/book/domain/BookUpdateRequest.java
  src/main/java/com/dodream/book/domain/BookUpdateResponse.java
  src/main/java/com/dodream/book/repository/BookRepository.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/book/service/BookmarkServiceImpl.java
  src/main/java/com/dodream/mypage/controller/MyPageBookController.java
  src/main/java/com/dodream/mypage/service/MyPageBookService.java
  src/main/java/com/dodream/mypage/service/MyPageBookServiceImpl.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: ✨ Feature, ✅ Test

#84 [스터디-페이지네이션] 페이징 성능 개선
  src/main/java/com/dodream/DodreamSampleApplication.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/study/controller/StudyController.java
  src/main/java/com/dodream/study/domain/StudyMemberResponse.java
  src/main/java/com/dodream/study/domain/StudyResponse.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/repository/StudyRepository.java
  src/main/java/com/dodream/study/service/StudyService.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/test/java/com/dodream/study/service/StudyServiceImplTest.java
Labels: 🐞 Bugfix, ✨ Feature, 🎤 Perform

#86 [기능 개발 - 스터디방 메인 페이지] 공지사항 CRUD
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/NoticeController.java
  src/main/java/com/dodream/study/domain/NoticeRequest.java
  src/main/java/com/dodream/study/domain/NoticeResponse.java
  src/main/java/com/dodream/study/domain/UpdateNoticeRequest.java
  src/main/java/com/dodream/study/domain/UpdateNoticeResponse.java
  src/main/java/com/dodream/study/entity/Notice.java
  src/main/java/com/dodream/study/repository/NoticeRepository.java
  src/main/java/com/dodream/study/service/NoticeService.java
  src/main/java/com/dodream/study/service/NoticeServiceImpl.java
Labels: ✨ Feature

#87 [기능 개발 - 문제집] 문제집 댓글 좋아요 기능 / 좋아요 순으로 댓글 조회
  src/main/java/com/dodream/book/controller/BookCommentController.java
  src/main/java/com/dodream/book/controller/BookCommentLikeController.java
  src/main/java/com/dodream/book/domain/BookCommentLikeResponse.java
  src/main/java/com/dodream/book/repository/BookCommentLikeRepository.java
  src/main/java/com/dodream/book/repository/BookCommentRepository.java
  src/main/java/com/dodream/book/service/BookCommentLikeService.java
  src/main/java/com/dodream/book/service/BookCommentLikeServiceImpl.java
  src/main/java/com/dodream/book/service/BookCommentService.java
  src/main/java/com/dodream/book/service/BookCommentServiceImpl.java
  src/test/java/com/dodream/book/repository/BookCommentLikeRepositoryTest.java
  src/test/java/com/dodream/book/repository/BookCommentRepositoryTest.java
  src/test/java/com/dodream/book/service/BookCommentLikeServiceTest.java
  src/test/java/com/dodream/book/service/BookCommentServiceTest.java
Labels: ✨ Feature, ✅ Test

#91 [기능 개발 - 문제집] 특정 문제집의 문제 CRUD
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/controller/QuestionController.java
  src/main/java/com/dodream/book/domain/QuestionListResponse.java
  src/main/java/com/dodream/book/domain/QuestionRequest.java
  src/main/java/com/dodream/book/domain/QuestionResponse.java
  src/main/java/com/dodream/book/entity/Question.java
  src/main/java/com/dodream/book/repository/QuestionRepository.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/book/service/QuestionService.java
  src/main/java/com/dodream/book/service/QuestionServiceImpl.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/test/java/com/dodream/book/repository/BookCommentLikeRepositoryTest.java
  src/test/java/com/dodream/book/repository/BookCommentRepositoryTest.java
  src/test/java/com/dodream/book/repository/BookRepositoryTest.java
  src/test/java/com/dodream/book/repository/QuestionRepositoryTest.java
  src/test/java/com/dodream/book/service/QuestionServiceTest.java
Labels: ✨ Feature, ✅ Test

#92 [기능개발 - 스터디 문제 페이지] 누군가의 답변 조회
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/StudyUserAnswerController.java
  src/main/java/com/dodream/study/domain/StudyUserAnswerResponse.java
  src/main/java/com/dodream/study/entity/StudyUserAnswer.java
  src/main/java/com/dodream/study/repository/StudyUserAnswerRepository.java
  src/main/java/com/dodream/study/service/StudyUserAnswerService.java
  src/main/java/com/dodream/study/service/StudyUserAnswerServiceImpl.java
Labels: ✨ Feature

#94 [기능 개발 - 스터디] 공지사항 댓글 CRUD + 인기 스터디 조회 + 스터디 멤버 조회
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/NoticeCommentController.java
  src/main/java/com/dodream/study/controller/NoticeCommentLikeController.java
  src/main/java/com/dodream/study/controller/StudyController.java
  src/main/java/com/dodream/study/controller/StudyMemberController.java
  src/main/java/com/dodream/study/domain/NoticeCommentLikeResponse.java
  src/main/java/com/dodream/study/domain/NoticeCommentRequest.java
  src/main/java/com/dodream/study/domain/NoticeCommentResponse.java
  src/main/java/com/dodream/study/domain/NoticeCommentUpdateRequest.java
  src/main/java/com/dodream/study/domain/NoticeCommentUpdateResponse.java
  src/main/java/com/dodream/study/domain/StudyMemberRequest.java
  src/main/java/com/dodream/study/domain/StudyMemberResponse.java
  src/main/java/com/dodream/study/entity/NoticeComment.java
  src/main/java/com/dodream/study/entity/NoticeCommentLike.java
  src/main/java/com/dodream/study/repository/NoticeCommentLikeRepository.java
  src/main/java/com/dodream/study/repository/NoticeCommentRepository.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/service/NoticeCommentLikeService.java
  src/main/java/com/dodream/study/service/NoticeCommentLikeServiceImpl.java
  src/main/java/com/dodream/study/service/NoticeCommentService.java
  src/main/java/com/dodream/study/service/NoticeCommentServiceImpl.java
  src/main/java/com/dodream/study/service/StudyMemberService.java
  src/main/java/com/dodream/study/service/StudyMemberServiceImpl.java
  src/main/java/com/dodream/study/service/StudyService.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
Labels: ✨ Feature, 🎤 Perform

#97 [테스트 - 공지사항 댓글, 좋아요] 공지사항 기능 테스트
  src/main/java/com/dodream/study/domain/NoticeRequest.java
  src/test/java/com/dodream/study/repository/NoticeCommentLikeRepositoryTest.java
  src/test/java/com/dodream/study/repository/NoticeCommentRepositoryTest.java
  src/test/java/com/dodream/study/repository/NoticeRepositoryTest.java
  src/test/java/com/dodream/study/service/NoticeCommentLikeServiceTest.java
  src/test/java/com/dodream/study/service/NoticeCommentServiceTest.java
  src/test/java/com/dodream/study/service/NoticeServiceTest.java
Labels: ✅ Test

#99 [기능 개발 - 문제집] 문제 풀기 / 평가하기
  src/main/java/com/dodream/book/controller/UserAnswerController.java
  src/main/java/com/dodream/book/domain/AnswerDetailsResponse.java
  src/main/java/com/dodream/book/domain/EvaluationRequest.java
  src/main/java/com/dodream/book/domain/UserAnswerRequest.java
  src/main/java/com/dodream/book/domain/UserAnswerResponse.java
  src/main/java/com/dodream/book/entity/UserAnswer.java
  src/main/java/com/dodream/book/repository/UserAnswerRepository.java
  src/main/java/com/dodream/book/service/UserAnswerService.java
  src/main/java/com/dodream/book/service/UserAnswerServiceImpl.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/test/java/com/dodream/book/repository/UserAnswerRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#101 [기능 개발 - 문제집] 문제를 내 문제집에 추가 / 내 스터디에 추가하기
  src/main/java/com/dodream/book/controller/QuestionController.java
  src/main/java/com/dodream/book/controller/UserAnswerController.java
  src/main/java/com/dodream/book/domain/AddToMyBooksRequest.java
  src/main/java/com/dodream/book/domain/AddToMyBooksResponse.java
  src/main/java/com/dodream/book/domain/AddToStudiesRequest.java
  src/main/java/com/dodream/book/service/QuestionService.java
  src/main/java/com/dodream/book/service/QuestionServiceImpl.java
  src/main/java/com/dodream/book/service/UserAnswerService.java
  src/main/java/com/dodream/book/service/UserAnswerServiceImpl.java
Labels: ✨ Feature

#103 [기능 개발 - 문제집] 사용자가 푼 문제 제외 조회 / 제목으로 문제 검색
  src/main/java/com/dodream/book/controller/QuestionController.java
  src/main/java/com/dodream/book/domain/EvaluationResponse.java
  src/main/java/com/dodream/book/domain/QuestionListResponse.java
  src/main/java/com/dodream/book/repository/QuestionRepository.java
  src/main/java/com/dodream/book/repository/UserAnswerRepository.java
  src/main/java/com/dodream/book/service/QuestionService.java
  src/main/java/com/dodream/book/service/QuestionServiceImpl.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/test/java/com/dodream/book/service/QuestionServiceTest.java
Labels: ✨ Feature

#104 [기능개발 - 스터디 문제 페이지] 누군가의 답변 페이지 댓글 CRUD , 좋아요
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/QueCommentController.java
  src/main/java/com/dodream/study/controller/QueCommentLikeController.java
  src/main/java/com/dodream/study/domain/QueCommentLikeResponse.java
  src/main/java/com/dodream/study/domain/QueCommentRequest.java
  src/main/java/com/dodream/study/domain/QueCommentResponse.java
  src/main/java/com/dodream/study/domain/QueCommentUpdateRequest.java
  src/main/java/com/dodream/study/domain/QueCommentUpdateResponse.java
  src/main/java/com/dodream/study/entity/QueComment.java
  src/main/java/com/dodream/study/repository/QueCommentLikeRepository.java
  src/main/java/com/dodream/study/repository/QueCommentRepository.java
  src/main/java/com/dodream/study/service/QueCommentLikeService.java
  src/main/java/com/dodream/study/service/QueCommentLikeServiceImpl.java
  src/main/java/com/dodream/study/service/QueCommentService.java
  src/main/java/com/dodream/study/service/QueCommentServiceImpl.java
Labels: ✨ Feature

#107 [기능 개발 - 메인페이지] 인기 문제집 조회 / 문제집+스터디 검색 기능
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/domain/BookResponse.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/main/controller/MainController.java
  src/main/java/com/dodream/main/domain/SearchResponse.java
  src/main/java/com/dodream/main/repository/MainRepository.java
  src/main/java/com/dodream/main/service/SearchService.java
  src/main/java/com/dodream/main/service/SearchServiceImpl.java
Labels: ✨ Feature

#110 [기능 개발 - 스터디] 스터디방 관리자 기능 + 스터디 가입 관련 기능 개발
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/study/controller/StudyController.java
  src/main/java/com/dodream/study/controller/StudyMemberController.java
  src/main/java/com/dodream/study/domain/StudyMemberRequest.java
  src/main/java/com/dodream/study/domain/StudyMemberResponse.java
  src/main/java/com/dodream/study/domain/StudyMemberUpdateRequest.java
  src/main/java/com/dodream/study/domain/StudyMemberUpdateResponse.java
  src/main/java/com/dodream/study/entity/StudyMember.java
  src/main/java/com/dodream/study/repository/StudyMemberRepository.java
  src/main/java/com/dodream/study/service/NoticeCommentServiceImpl.java
  src/main/java/com/dodream/study/service/StudyMemberService.java
  src/main/java/com/dodream/study/service/StudyMemberServiceImpl.java
  src/main/java/com/dodream/study/service/StudyService.java
  src/main/java/com/dodream/study/service/StudyServiceImpl.java
  src/test/java/com/dodream/study/service/StudyServiceImplTest.java
Labels: ✨ Feature

#112 [버그 수정] 문제집 삭제 시 관련된 entity 삭제 안되는 이슈 확인
  src/main/java/com/dodream/book/entity/Book.java
  src/main/java/com/dodream/book/entity/BookComment.java
  src/main/java/com/dodream/book/entity/Question.java
  src/main/java/com/dodream/book/entity/UserAnswer.java
  src/main/java/com/dodream/book/repository/BookCommentLikeRepository.java
  src/main/java/com/dodream/book/repository/BookCommentRepository.java
  src/main/java/com/dodream/book/repository/BookmarkRepository.java
  src/main/java/com/dodream/book/repository/UserAnswerRepository.java
  src/main/java/com/dodream/book/repository/UserBookRepository.java
  src/main/java/com/dodream/book/service/BookCommentServiceImpl.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/book/service/QuestionServiceImpl.java
  src/main/java/com/dodream/study/repository/StudyUserAnswerRepository.java
Labels: 🐞 Bugfix

#116 [기능 개발 - 마이페이지] 프로필 이미지 수정
  build.gradle
  src/main/java/com/dodream/common/config/AwsS3Config.java
  src/main/java/com/dodream/common/exception/BaseException.java
  src/main/java/com/dodream/common/exception/ErrorCode.java
  src/main/java/com/dodream/mypage/controller/MyPageController.java
  src/main/java/com/dodream/mypage/service/MyPageService.java
  src/main/java/com/dodream/mypage/service/MyPageServiceImpl.java
Labels: ⚙️ Setting, ✨ Feature

#118 [기능 개발 - 스터디] 스터디방 메인 페이지 개발 + 스터디 기능 이슈 수정
  src/main/java/com/dodream/book/repository/UserAnswerRepository.java
  src/main/java/com/dodream/study/controller/StudyUserQueAnswerController.java
  src/main/java/com/dodream/study/domain/StudyUserQueAnswerResponse.java
  src/main/java/com/dodream/study/entity/Study.java
  src/main/java/com/dodream/study/service/StudyMemberServiceImpl.java
  src/main/java/com/dodream/study/service/StudyQueUserAnswerService.java
  src/main/java/com/dodream/study/service/StudyQueUserAnswerServiceImpl.java
  src/main/java/com/dodream/user/entity/User.java
Labels: 🐞 Bugfix, ✨ Feature

#120 [기능 수정 - 로그인] 토큰 재발급 기능
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/main/java/com/dodream/security/JwtProvider.java
  src/main/java/com/dodream/user/controller/UserController.java
  src/main/java/com/dodream/user/service/UserService.java
  src/main/java/com/dodream/user/service/UserServiceImpl.java
Labels: 🐞 Bugfix

#122 [기능 개발 - 문제집] 문제집 개별 조회
  src/main/java/com/dodream/book/controller/BookController.java
  src/main/java/com/dodream/book/service/BookService.java
  src/main/java/com/dodream/book/service/BookServiceImpl.java
  src/main/java/com/dodream/common/config/WebSecurityConfig.java
  src/test/java/com/dodream/book/service/BookServiceTest.java
Labels: ✨ Feature, ✅ Test
